baseURL = "http://localhost:1313/"
languageCode = "en-us"
title = "Now Playing"
mainSections = ["a"]
paginate = 16
disableKinds = ["taxonomy", "taxonomyTerm"]
[params]
  description = "Collection of Handpicked Albums by Hécate"
  [params.author]
    name = "Hécate Moonlight"
    url = "https://glitchbra.in"
  # [params.creator]
  #   name = "Guérilla.Studio"
  #   url = "https://guerilla.studio"

[imaging]
quality = 95
[security]
  [security.funcs]
  getenv = [ "^HUGO_", "CONTEXT", "URL" ]
